// Generated by ReScript, PLEASE EDIT WITH CARE


function theme(i) {
  switch (i) {
    case 0 :
      return 152.0;
    case 1 :
      return 0.62;
    case 2 :
      return 0.42;
    case 3 :
      return 2.0;
    case 4 :
      return 1240.0;
    case 5 :
      return 17.0;
    case 6 :
      return 22.0;
    case 7 :
      return 16.0;
    default:
      return -1.0;
  }
}

function hot_score(votes, answers, views, ageDays) {
  let base = votes * 3.0 + answers * 5.0 + views / 100.0;
  return base / (1.0 + ageDays / 30.0);
}

let qaEncoder = new TextEncoder();

function qaLower(b) {
  if (b >= 65 && b <= 90) {
    return b + 32 | 0;
  } else {
    return b;
  }
}

function search_score(query, text) {
  let q = qaEncoder.encode(query);
  let t = qaEncoder.encode(text);
  let qLen = q.length;
  if (qLen === 0) {
    return 0.0;
  }
  let tLen = t.length;
  let score = 0.0;
  for (let i = 0; i < qLen; ++i) {
    let c = qaLower(q[i]);
    if (c !== 32) {
      let n = 0.0;
      for (let j = 0; j < tLen; ++j) {
        if (qaLower(t[j]) === c) {
          n = n + 1.0;
        }
      }
      score = score + n;
    }
  }
  return score / qLen;
}

export {
  theme,
  hot_score,
  qaEncoder,
  qaLower,
  search_score,
}
/* qaEncoder Not a pure module */
